import { QuotaPackage, AITokenPackage, CourierOption } from '@/types';

export const quotaPackages: QuotaPackage[] = [
  // Non-Pro Packages
  {
    id: 'pkg-nonpro-50',
    code: 'NONPRO_50',
    name: 'Top-Up 50 Order (Non-Pro)',
    quota: 50,
    originalPrice: 50000,
    price: 50000,
    pricePerOrder: 1000,
    discountPercent: 0,
    badge: 'Starter Non-Pro',
    tier: 'NON_PRO',
  },
  {
    id: 'pkg-nonpro-100',
    code: 'NONPRO_100',
    name: 'Top-Up 100 Order (Non-Pro)',
    quota: 100,
    originalPrice: 100000,
    price: 100000,
    pricePerOrder: 1000,
    discountPercent: 0,
    badge: 'Standar Non-Pro',
    tier: 'NON_PRO',
  },
  // Pro Member Packages (Hemat 75%)
  {
    id: 'pkg-pro-200',
    code: 'PRO_200',
    name: 'Top-Up 200 Order (Pro)',
    quota: 200,
    bonusOrders: 50,
    originalPrice: 200000,
    price: 50000,
    pricePerOrder: 250,
    discountPercent: 75,
    badge: 'Paling Laris',
    popular: true,
    tier: 'PRO',
  },
  {
    id: 'pkg-pro-400',
    code: 'PRO_400',
    name: 'Top-Up 400 Order (Pro)',
    quota: 400,
    bonusOrders: 100,
    originalPrice: 400000,
    price: 100000,
    pricePerOrder: 250,
    discountPercent: 75,
    badge: 'Best Value',
    tier: 'PRO',
  },
  {
    id: 'pkg-pro-1000',
    code: 'PRO_1000',
    name: 'Top-Up 1.000 Order (Pro)',
    quota: 1000,
    bonusOrders: 250,
    originalPrice: 1000000,
    price: 250000,
    pricePerOrder: 250,
    discountPercent: 75,
    badge: 'Sultan Juragan',
    tier: 'PRO',
  },
];

export const aiTokenPackages: AITokenPackage[] = [
  {
    code: 'AI_PHOTO_10',
    name: '10x Foto Model Studio AI',
    category: 'PHOTO_MODEL',
    tokenAmount: 10,
    price: 50000,
    badge: 'Katalog Viral',
    description: 'Ubah foto produk HP menjadi foto katalog studio profesional dengan model manusia AI realistis.',
  },
  {
    code: 'AI_LANDING_3',
    name: '3x AI Landing Page Generator',
    category: 'LANDING_PAGE',
    tokenAmount: 3,
    price: 49000,
    badge: 'Siap Iklan Ads',
    description: 'Generate 3 landing page konversi tinggi siap iklan Meta & TikTok dalam hitungan detik.',
  },
  {
    code: 'AI_CHAT_1000',
    name: '1.000 Kuota Chat Jaga AI WhatsApp',
    category: 'CS_CHAT',
    tokenAmount: 1000,
    price: 49000,
    badge: 'Autopilot 24/7',
    description: 'Kuota percakapan bot AI CS WA 24/7 untuk menjawab ongkir, cek resi & closing pembeli.',
  },
];

export const destinationOptions = [
  { city: 'Kota Jakarta Selatan', district: 'Kebayoran Baru', baseRate: 11000 },
  { city: 'Kota Jakarta Barat', district: 'Kebon Jeruk', baseRate: 11000 },
  { city: 'Kota Depok', district: 'Beji', baseRate: 13000 },
  { city: 'Kota Tangerang Selatan', district: 'Pamulang', baseRate: 13000 },
  { city: 'Kota Bandung', district: 'Coblong', baseRate: 9000 },
  { city: 'Kota Surabaya', district: 'Gubeng', baseRate: 18000 },
  { city: 'Kota Semarang', district: 'Banyumanik', baseRate: 16000 },
  { city: 'Kota Medan', district: 'Medan Baru', baseRate: 28000 },
  { city: 'Kota Makassar', district: 'Panakkukang', baseRate: 34000 },
];

export const MASTER_COURIERS: CourierOption[] = [
  {
    code: 'JNT',
    name: 'J&T Express',
    service: 'EZ (Reguler 1-2 Hari)',
    category: 'REGULER',
    description: 'Jangkauan luas ke seluruh pelosok Indonesia dengan penjemputan cepat.',
    defaultRateOffset: 2000,
  },
  {
    code: 'JNE',
    name: 'JNE',
    service: 'Reguler (1-2 Hari)',
    category: 'REGULER',
    description: 'Pelopor ekspedisi terpercaya dengan jaringan agen terlengkap.',
    defaultRateOffset: 1000,
  },
  {
    code: 'SICEPAT',
    name: 'SiCepat',
    service: 'REG (1-2 Hari)',
    category: 'REGULER',
    description: 'Tarif bersahabat dan kecepatan pengiriman prima.',
    defaultRateOffset: 0,
  },
  {
    code: 'ANTERAJA',
    name: 'Anteraja',
    service: 'Regular (1-3 Hari)',
    category: 'REGULER',
    description: 'Layanan terintegrasi dengan penjemputan langsung ke lokasi seller.',
    defaultRateOffset: 0,
  },
  {
    code: 'JTR',
    name: 'JTR (JNE Trucking)',
    service: 'Kargo Muatan Berat (3-5 Hari)',
    category: 'KARGO',
    description: 'Spesialis pengiriman barang besar & berat (≥ 10 kg) dengan tarif kargo hemat.',
    defaultRateOffset: 5000,
  },
  {
    code: 'JNTCARGO',
    name: 'J&T Cargo',
    service: 'Kargo Paket Besar (2-4 Hari)',
    category: 'KARGO',
    description: 'Pengiriman paket besar & partai grosir cepat ke seluruh kota di Indonesia.',
    defaultRateOffset: 7000,
  },
  {
    code: 'INDAH',
    name: 'Indah Logistik Cargo',
    service: 'Kargo Partai Besar (3-6 Hari)',
    category: 'KARGO',
    description: 'Pilihan utama distributor dan pabrik untuk muatan koli besar antarpulau.',
    defaultRateOffset: 4000,
  },
];

